# Numpy Zero To Expert
### hands-on practicals of numpy and numpy arrays


+ Task-0: Create Basic array from diffrent data-type

In [2]:
# import statements for numpy
# import numpy

# import specific methods from numpy
# from numpy import array

# import whole package with alias
import numpy as np

In [3]:
# basic example to create array with list/tuple
arr_li = np.array([1,2,3,4,5,6,7,8])
arr_tp = np.array((1,2,3,4,5,6,7,8))
print(arr_li)
print(arr_tp)

# this statement print array type. (dtype is attribute of np array.)
print(arr_li.dtype)
print(arr_tp.dtype)



[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
int64
int64


In [89]:
# basic example to create array with set
arr_set = np.array({1,2,3,4,5,6,7,8})
print(arr_set)

# this statement print array type. (dtype is attribute of np array.)
print(arr_set.dtype)


{1, 2, 3, 4, 5, 6, 7, 8}
object


In [90]:
# basic example to try create array with dict 
arr_dict = np.array({"1":2,"3":4,"5":6,"7":8})
print(arr_dict)

# this statement print array type. (dtype is attribute of np array.)
print(arr_dict.dtype)
print(type(arr_dict))


{'1': 2, '3': 4, '5': 6, '7': 8}
object
<class 'numpy.ndarray'>


In [91]:
# basic example to try create array with dict 
arr_str = np.array("python")
print(arr_str)

# this statement print array type. (dtype is attribute of np array.)
print(arr_str.dtype)
print(type(arr_str))


python
<U6
<class 'numpy.ndarray'>


+ Task-1 : create 1D,2D and 3D array with array method and try some basic attributes.

In [4]:
arr_1D = np.array([1,2,3,4,5]) #normal array
arr_2D = np.array([[11,12,13],[14,15,16],[17,18,19]]) #matrix array with row and columns
arr_3D = np.array([[[20,21,22],[23,24,25]],[[26,27,28],[29,30,31]],[[32,33,34],[35,36,37]]]) # 3-D aray like cube or tensor

# print array
print(arr_1D,"\n")
print(arr_2D,"\n")
print(arr_3D,"\n")

# print array shape
print("shape:")
print(arr_1D.shape)
print(arr_2D.shape)
print(arr_3D.shape)

# print dimensions of array
print("dimensions:")
print(arr_1D.ndim)
print(arr_2D.ndim)
print(arr_3D.ndim)

# print size of array
print("size:")
print(arr_1D.size)
print(arr_2D.size)
print(arr_3D.size)

# print size in bytes of one elements in arrays
print("size of one elements:")
print(arr_1D.itemsize)
print(arr_2D.itemsize)
print(arr_3D.itemsize)

#print total bytes consume by array
print("total byte consume by arrays:") 
print(arr_1D.nbytes)
print(arr_2D.nbytes)
print(arr_3D.nbytes)
print("formula : number of elements * itemsize")

[1 2 3 4 5] 

[[11 12 13]
 [14 15 16]
 [17 18 19]] 

[[[20 21 22]
  [23 24 25]]

 [[26 27 28]
  [29 30 31]]

 [[32 33 34]
  [35 36 37]]] 

shape:
(5,)
(3, 3)
(3, 2, 3)
dimensions:
1
2
3
size:
5
9
18
size of one elements:
8
8
8
total byte consume by arrays:
40
72
144
formula : number of elements * itemsize


+ Task-2 : try different methods of array

Summary Table of Math/Statistics Methods

| Method        | Description             | Example             | 
|---------------|--------------------------|----------------------|
| sum(axis)   | Total along an axis      | arr.sum(axis=0)   | 
| mean(axis)  | Average along an axis    | arr.mean(axis=1)  | 
| std(axis)   | Standard deviation       | arr.std(axis=0)   | 
| var(axis)   | Variance                 | arr.var(axis=1)   | 
| min(axis)   | Minimum value            | arr.min(axis=0)   | 
| max(axis)   | Maximum value            | arr.max(axis=1)   | 
| argmin(axis)| Index of min             | arr.argmin(axis=0)| 
| argmax(axis)| Index of max             | arr.argmax(axis=1)| 
| prod(axis)  | Product of values        | arr.prod(axis=1)  | 
| cumsum(axis)| Cumulative sum           | arr.cumsum(axis=1)| 
| cumprod(axis)| Cumulative product      | arr.cumprod(axis=0)|

In [93]:
# note : Axis=0 --> columns wise 
# note : Axis=1 --> Rows wise 

arr_1D = np.array([1,2,3,4,5]) #normal array
arr_2D = np.array([[11,12,13],[14,15,16],[17,18,19]]) #matrix array with row and columns
arr_3D = np.array([[[20,21,22],[23,24,25],[1,2,3]],[[26,27,28],[29,30,31],[4,5,6]],[[32,33,34],[35,36,37],[7,8,9]]]) # 3-D aray like cube or tensor

# print dimensions of array
print("dimensions:")
print(arr_1D.ndim)
print(arr_2D.ndim)
print(arr_3D.ndim)

# min function
print("minimum:")
print(arr_1D.min())
print(arr_2D.min(axis=0)) 
print(arr_3D.min(axis=1))

# max function
print("maximum:")
print(arr_1D.max())
print(arr_2D.max(axis=1))
print(arr_3D.max(axis=0))

# sum function
print("Sum:")
print(arr_1D.sum())
print(arr_2D.sum(axis=0))
print(arr_3D.sum(axis=1))

# mean function
print("mean:")
print(arr_1D.mean())
print(arr_2D.mean(axis=0))
print(arr_3D.mean(axis=1))

# std function (standard deviation)
print("standard deviation:")
print(arr_1D.std())
print(arr_2D.std(axis=0))
print(arr_3D.std(axis=1))

# var function (variance)
print("variance:")
print(arr_1D.var())
print(arr_2D.var(axis=0))
print(arr_3D.var(axis=1))

# argmin function : return index of minimum elements
print("argmin:")
print(arr_1D.argmin(),arr_1D.min())
print(arr_2D.argmin(),arr_2D.min())
print(arr_3D.argmin(),arr_3D.min())

# argmax function : return index of maximum elements
print("argmax:")
print(arr_1D.argmax(),arr_1D.max())
print(arr_2D.argmax(),arr_2D.max())
print(arr_3D.argmax(),arr_3D.max())

# prod function (product)
print("product:")
print(arr_1D.prod())
print(arr_2D.prod(axis=1))
print(arr_3D.prod(axis=0))

# cumsum function (cumulative sum)
print("cumulative sum:")
print(arr_1D.cumsum())
print(arr_2D.cumsum(axis=1))
print(arr_3D.cumsum(axis=0))

# cumprod function (cumulative product)
print("cumulative product:")
print(arr_1D.cumprod())
print(arr_2D.cumprod(axis=1))
print(arr_3D.cumprod(axis=0))

dimensions:
1
2
3
minimum:
1
[11 12 13]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
maximum:
5
[13 16 19]
[[32 33 34]
 [35 36 37]
 [ 7  8  9]]
Sum:
15
[42 45 48]
[[44 47 50]
 [59 62 65]
 [74 77 80]]
mean:
3.0
[14. 15. 16.]
[[14.66666667 15.66666667 16.66666667]
 [19.66666667 20.66666667 21.66666667]
 [24.66666667 25.66666667 26.66666667]]
standard deviation:
1.4142135623730951
[2.44948974 2.44948974 2.44948974]
[[ 9.7410928   9.7410928   9.7410928 ]
 [11.14550233 11.14550233 11.14550233]
 [12.55211359 12.55211359 12.55211359]]
variance:
2.0
[6. 6. 6.]
[[ 94.88888889  94.88888889  94.88888889]
 [124.22222222 124.22222222 124.22222222]
 [157.55555556 157.55555556 157.55555556]]
argmin:
0 1
0 11
6 1
argmax:
4 5
8 19
23 37
product:
120
[1716 3360 5814]
[[16640 18711 20944]
 [23345 25920 28675]
 [   28    80   162]]
cumulative sum:
[ 1  3  6 10 15]
[[11 23 36]
 [14 29 45]
 [17 35 54]]
[[[20 21 22]
  [23 24 25]
  [ 1  2  3]]

 [[46 48 50]
  [52 54 56]
  [ 5  7  9]]

 [[78 81 84]
  [87 90 93]
  [12 15 18]]]


+ Task-3 : Create arrys with diffrent menthods and fuctions.

